version: '3.7'
services:
  app:
    container_name: app
    volumes:
      - ./processors:/var/www
    build:
      context: ./app
      args:
        HOST_UID: 1000
    restart: always
    ports:
      - 9000
      - 8080:8080
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - nifi-kpgu
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:11.10
    restart: always
    environment:
      - TZ=UTC
      - POSTGRES_MULTIPLE_DATABASES=${KPGU_DATABASE_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 54328:5432
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    # - ./data/postgresql/data:/var/lib/postgresql/data
    build:
      context: ./postgres
    networks:
      - nifi-kpgu

networks:
  nifi-kpgu:
    name: nifi-kpgu-network
    driver: bridge